"""init

Revision ID: a5d0265f38a1
Revises: 
Create Date: 2019-02-27 14:23:18.707843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d0265f38a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('hash', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertparsemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('root', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('category_level_idx', 'category', ['level'], unique=False)
    op.create_index('category_lft_idx', 'category', ['lft'], unique=False)
    op.create_index('category_rgt_idx', 'category', ['rgt'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('telegram_key', sa.String(length=255), nullable=True),
    sa.Column('temp_key', sa.String(length=255), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parseditem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsermap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('root', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('last_crawling', sa.DateTime(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_category_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_category_association')
    op.drop_table('parsermap')
    op.drop_table('parseditem')
    op.drop_table('user')
    op.drop_table('link')
    op.drop_index('category_rgt_idx', table_name='category')
    op.drop_index('category_lft_idx', table_name='category')
    op.drop_index('category_level_idx', table_name='category')
    op.drop_table('category')
    op.drop_table('advertparsemap')
    op.drop_table('advert')
    # ### end Alembic commands ###
